upstream wordpress_backend {
    least_conn;
    server wordpress1:80;
    server wordpress2:80;
}

server {
    listen 443 ssl;
    server_name servidortesteo.xyz www.servidortesteo.xyz;

    ssl_certificate /etc/nginx/certificados/wordpress.crt;
    ssl_certificate_key /etc/nginx/certificados/wordpress.key;

    ssl_protocols TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 64M;

    location / {
        proxy_pass http://wordpress_backend;
        add_header X-Backend $upstream_addr always;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }
}
